# Compiler
CXX = g++
# The cpp flags
CXXFLAGS :=
Matrix_Multiply_Serial_Fixed_Values:
    # Compiling the application
	@echo "Compiling Matrix_Multiply_Serial_Fixed_Values"
	@$(CXX) $(CXXFLAGS) ./src/Matrix_Multiply_Serial.cpp -o ./bin/Matrix_Multiply_Serial.exe
	@echo "Done Compiling Matrix_Multiply_Serial"

	@echo "Running Matrix_Multiply_Serial.exe"
	@./bin/Matrix_Multiply_Serial.exe -A 3000x3000 -B 3000x3000